POST http://127.0.0.1:3000/api/auth/register
Content-Type: application/json

{
    "name":"coba",
    "email":"coba@gmail.com",
    "password":"cobacoba"
}


###

GET http://127.0.0.1:3000/api/contact